# Семинар 2

### 1. Основы NumPy
NumPy - это библиотека для работы с научными расчетами в Python. Она предоставляет возможность высокопроизводительной работы с многомерными массивами и инструменты, для работы с ними.  

#### **Создание массивов:**

In [ ]:
import numpy as np

one_dim_array = np.array([1, 2, 3])
two_dim_array = np.array([[1, 2, 3], [4, 5, 6]])
three_dim_array = np. array([[(1, 2, 3), (4, 5, 6)], [(7, 8, 9), (10, 11, 12)]])

print("1D array: ")
print(one_dim_array)

print("2D array: ")
print(two_dim_array)

print("3D array: ")
print(three_dim_array)

В NumPy есть возможность инициализировать массив нулей и массив единиц:

In [6]:
zeros = np.zeros((3, 4))
print(zeros)

ones = np.ones((2, 3, 4))
print(ones)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


Также можно созздавать массивы случайных чисел, пустые массивы и мн. др.  
  
Для указания типа элементов массива можно пользоваться входным полем dtype и его значениями, которые характеризуют тип значений:

In [ ]:
np.int64 # целочисленное значение
np.float32 # числа с 'плавающей точкой'
np.complex # комплексные числа
np.bool # True или False
np.object # объекты python
np.string_ # строковые значения фиксированной длинны
np.unicode_ # значения фиксированной длинны в юникоде

В NumPy, при создании объекта массива у него инициализируется еще ряд полей:

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.shape) #возвращает массив с измерениями массива
print(a.ndim) #возвращает размерность массива
print(a.size) # возвращает количество элементов массива


NumPy также умеет проводить арифметические функции с массивами, имеет ряд агрегационных функций, умеет сравнивать массивы поэлементно, производить сортировку и многое другое.

### 2. Линейная алгебра в SciPy
SciPy - это  еще одна библиотека для научных расчетов в Python. Она основана на базе библиотеки NumPy и является её расширением.  
Модуль для работы с линейной алгеброй в SciPy linalg включает в себя и расширяет
модуль linalg из NumPy.  
  
Начнем как обычно с импорта и инициализации массивов:

In [17]:
from scipy import linalg, sparse

# создадим базовый набор массивов
A = np.matrix(np.random.random((2, 2))) # матрица 2x2 со случайными значениями от 0 до 1
B = np.asmatrix(A) # копируем матрицу A
C = np.mat(np.random.random((10, 5)))
D = np.mat([[3, 4], [5, 6]])
print("A=\n%s" % A)
print("B=\n%s" % B)
print("C=\n%s" % C)
print("D=\n%s" % D)

A=
[[0.89334205 0.93912762]
 [0.26378725 0.05061431]]
B=
[[0.89334205 0.93912762]
 [0.26378725 0.05061431]]
C=
[[0.34220774 0.94876121 0.60381791 0.04700848 0.29539019]
 [0.49945328 0.36382262 0.68472202 0.57887806 0.57613935]
 [0.32363327 0.54795136 0.69396763 0.17534387 0.21387711]
 [0.95747763 0.89985942 0.90840668 0.74757111 0.43093495]
 [0.594679   0.07562995 0.96167055 0.51060774 0.93293493]
 [0.45783344 0.59628293 0.20368474 0.89968691 0.67023856]
 [0.87563817 0.34972513 0.00447343 0.90551814 0.74223414]
 [0.38842489 0.95194532 0.77911176 0.87914403 0.52293081]
 [0.19586376 0.51612186 0.50561873 0.45345935 0.14786394]
 [0.05879222 0.63305463 0.11867118 0.88570168 0.36021259]]
D=
[[3 4]
 [5 6]]


В линейной алгебре встречается ряд действий с матрицами, например нахождение определителя (детерминанта) матрицы, транспонирование матрицы и мн. др.  
Вот несколько примеров (**ВНИМАНИЕ! Для работы всех следующих кусков кода, требуется запустить предыдущий хотя бы один раз**):

In [30]:
print("Определитель матрицы A =\n%s" % linalg.det(A))
print("Транспонированная матрица  D =\n%s" % D.T)
print("Норма матрицы B = %s" % linalg.norm(B))
print("Ранг матрицы A = %s" % np.linalg.matrix_rank(C))

Определитель матрицы A =
-0.2025139964044584
Транспонированная матрица  D =
[[3 5]
 [4 6]]
Норма матрицы B = 1.3236941577397046
Ранг матрицы A = 2


Матричные функции:

In [41]:
print("D x 2 = \n%s\n---------------------" % np.multiply(D, 2))
print("D / 2 = \n%s\n---------------------" % np.divide(D, 2))
print("A + D = \n%s\n---------------------" % np.add(A, D))
print("D - A = \n%s\n---------------------" % np.subtract(D, A))
print("A x D = \n%s\n---------------------" % np.multiply(A, D))
print("D / A = \n%s\n---------------------" % np.divide(D, A))

D x 2 = 
[[ 6  8]
 [10 12]]
---------------------
D / 2 = 
[[1.5 2. ]
 [2.5 3. ]]
---------------------
A + D = 
[[3.89334205 4.93912762]
 [5.26378725 6.05061431]]
---------------------
D - A = 
[[2.10665795 3.06087238]
 [4.73621275 5.94938569]]
---------------------
A x D = 
[[2.68002615 3.75651048]
 [1.31893623 0.30368586]]
---------------------
D / A = 
[[  3.35817619   4.25927203]
 [ 18.95466929 118.54355071]]
---------------------
